// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineShop2.RMK;

#nullable disable

namespace OnlineShop2.RMK.Migrations
{
    [DbContext(typeof(RmkDbContext))]
    partial class RmkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");
#pragma warning restore 612, 618
        }
    }
}
